; Generated by Aether Compiler
; Target: x86_64 NASM assembly listing

; Extern declarations (hoisted from asm blocks)

bits 64
default rel


section .text

global _start
_start:
    mov      rbp, rsp
; call main()
    call main
; freestanding: just hlt after main returns
    hlt
    hlt

; function main (frame=16)
global main
main:
    push     rbp
    mov      rbp, rsp
    sub rsp, 16
    lea rax, [rel Lstr0]
    mov qword [rbp-8], rax
; default return
    mov      rsp, rbp
    pop      rbp
    ret

section .rodata
Lstr0: db "World", 0
