; Generated by Aether Compiler
; Target: Mach-O 64 (macOS)

; Extern declarations (hoisted from asm blocks)

default rel


section .text

global _aether_entry
_aether_entry:
    mov      rbp, rsp
; call main()
    call main
; macOS exit(rdi = rax)
    mov      rdi, rax
    mov      rax, 0x2000001
    syscall
    hlt

section .bss
__aether_heap_start: resq 1
__aether_heap_cur:   resq 1
__aether_heap_end:   resq 1
__aether_region_cur: resq 1
__aether_region_end: resq 1

section .text
; __aether_alloc(rdi: size) -> rax: ptr
; If region is active, bump from region first.
__aether_alloc:
    push     rbp
    mov      rbp, rsp
    add rdi, 15
    and rdi, ~15
    mov rax, [rel __aether_region_cur]
    test     rax, rax
    jz LA_heap
    lea rcx, [rax + rdi]
    cmp rcx, [rel __aether_region_end]
    jbe LA_region_ok
    jmp LA_heap
LA_region_ok:
    mov [rel __aether_region_cur], rcx
    mov      rsp, rbp
    pop      rbp
    ret
LA_heap:
    push     rdi
LA_init:
    mov      rdi, 0
    mov      rsi, 65536
    mov      rdx, 3
    mov      r10, 0x1002
    mov      r8, -1
    xor      r9, r9
    mov      rax, 0x20000C5
    syscall
    mov [rel __aether_heap_start], rax
    lea rcx, [rax + 8]
    mov [rel __aether_heap_cur], rcx
    lea rcx, [rax + 65536]
    mov [rel __aether_heap_end], rcx
LA_try:
    mov rax, [rel __aether_heap_cur]
    lea rcx, [rax + rdi]
    cmp rcx, [rel __aether_heap_end]
    jbe LA_ok
    mov      rdi, 0
    mov      rsi, 65536
    mov      rdx, 3
    mov      r10, 0x1002
    mov      r8, -1
    xor      r9, r9
    mov      rax, 0x20000C5
    syscall
    lea rcx, [rax + 8]
    mov [rel __aether_heap_cur], rcx
    lea rcx, [rax + 65536]
    mov [rel __aether_heap_end], rcx
LA_ok:
    mov rax, [rel __aether_heap_cur]
    add [rel __aether_heap_cur], rdi
    mov      rsp, rbp
    pop      rbp
    ret

; __aether_free(rdi: ptr) — no-op (bump allocator)
__aether_free:
    ret

; __aether_concat(left: ptr, right: ptr) -> rax: ptr
; Concatenates two null-terminated strings, returns new string
__aether_concat:
    push     rbp
    mov      rbp, rsp
    push     r12
    push     r13
    push     r14
    mov r12, [rbp+16]
    mov r13, [rbp+24]
    xor      rcx, rcx
LA_concat_strlen_left:
    cmp byte [r12+rcx], 0
    jz LA_concat_left_done
    inc      rcx
    jmp LA_concat_strlen_left
LA_concat_left_done:
    mov      r14, rcx
    xor      rcx, rcx
LA_concat_strlen_right:
    cmp byte [r13+rcx], 0
    jz LA_concat_right_done
    inc      rcx
    jmp LA_concat_strlen_right
LA_concat_right_done:
    lea      rdi, [r14+rcx+1]
    push     rcx
    call __aether_alloc
    pop      rcx
    mov      rdi, rax
    mov      rsi, r12
    mov      rdx, r14
    call LA_concat_memcpy
    add      rdi, r14
    mov      rsi, r13
    mov      rdx, rcx
    call LA_concat_memcpy
    mov byte [rdi+rcx], 0
    pop      r14
    pop      r13
    pop      r12
    mov      rsp, rbp
    pop      rbp
    ret

LA_concat_memcpy:
    xor      rcx, rcx
LA_concat_memcpy_loop:
    cmp rcx, rdx
    jae LA_concat_memcpy_done
    mov al, [rsi+rcx]
    mov [rdi+rcx], al
    inc      rcx
    jmp LA_concat_memcpy_loop
LA_concat_memcpy_done:
    ret

; function main (frame=16)
global main
main:
    push     rbp
    mov      rbp, rsp
    sub rsp, 16
    lea rax, [rel Lstr0]
    mov qword [rbp-8], rax
    lea rax, [rel Lstr1]
    push     rax
    mov      rax, 0
    push     rax
    lea rax, [rel Lstr2]
    pop      rcx
; string concat
    push     rcx
    push     rax
    call __aether_concat
    add rsp, 16
    pop      rcx
; string concat
    push     rcx
    push     rax
    call __aether_concat
    add rsp, 16
    mov qword [rbp-16], rax
; default return
    mov      rsp, rbp
    pop      rbp
    ret

section .rodata
Lstr2: db "Hello ", 0
Lstr1: db "!", 0
Lstr0: db "World", 0
