#include "codegen_internal.h"
/* ================================================================
 * Top-level code generation — target-aware
 * ================================================================ */
const char *codegen_generate(Codegen *cg, AstNode *program) {
    cg_comment(cg, "Generated by Aether Compiler");
    cg_write_fmt(cg, "; Target: %s\n\n", target_name(cg->target));

    /* First pass: collect all extern declarations from asm blocks */
    /* and emit them at the top level where NASM requires them */
    cg_write(cg, "; Extern declarations (hoisted from asm blocks)\n");
    for (int i = 0; i < program->data.list.count; i++) {
        AstNode *node = program->data.list.items[i];
        if (node->type == NODE_FUNC_DECL && node->data.func.body) {
            collect_externs_from_block(cg, node->data.func.body);
        }
    }
    /* For host targets: declare extern C helper functions */
    if (cg->target == TARGET_MACHO64 || cg->target == TARGET_ELF64_HOST) {
        cg_write(cg, "; C helper functions (from segfault_helper.o)\n");
        /* Mach-O: C compiler prepends _ to symbols, NASM does NOT for Mach-O.
         * So C function aether_initSegfault → object _aether_initSegfault.
         * NASM extern _aether_initSegfault → object _aether_initSegfault. ✓ */
        if (cg->target == TARGET_MACHO64) {
            cg_write(cg, "extern _aether_initSegfault\n");
            cg_write(cg, "extern _aether_printStacktrace\n");
            cg_write(cg, "extern _aether_setJmpBuf\n");
            cg_write(cg, "extern _aether_clearJmpBuf\n");
        } else {
            cg_write(cg, "extern aether_initSegfault\n");
            cg_write(cg, "extern aether_printStacktrace\n");
            cg_write(cg, "extern aether_setJmpBuf\n");
            cg_write(cg, "extern aether_clearJmpBuf\n");
        }
    }
    cg_write(cg, "\n");

    /* Emit extern declarations for imported .aelib functions (body == NULL) */
    bool has_aelib_externs = false;
    for (int i = 0; i < program->data.list.count; i++) {
        AstNode *node = program->data.list.items[i];
        if (node->type == NODE_FUNC_DECL && !node->data.func.body) {
            if (!has_aelib_externs) {
                cg_comment(cg, "Imported .aelib function declarations");
                has_aelib_externs = true;
            }
            const char *fname = arena_strndup(cg->arena,
                node->data.func.name->data.ident.name.data,
                node->data.func.name->data.ident.name.len);
            if (cg->target == TARGET_MACHO64) {
                cg_write_fmt(cg, "extern %s\n", fname);
            } else {
                cg_write_fmt(cg, "extern %s\n", fname);
            }
        }
    }
    if (has_aelib_externs) cg_write(cg, "\n");

    /* Build struct layouts from top-level declarations */
    for (int i = 0; i < program->data.list.count; i++) {
        AstNode *node = program->data.list.items[i];
        if (node->type == NODE_STRUCT_DECL || node->type == NODE_CLASS_DECL) {
            build_struct_layout(cg->arena, node);
        } else if (node->type == NODE_ENUM_DECL) {
            build_enum_layout(cg->arena, node);
        }
    }

    /* Scan for @test functions and check if main() exists */
    bool has_main = false;
    int test_func_count = 0;
    for (int i = 0; i < program->data.list.count; i++) {
        AstNode *node = program->data.list.items[i];
        if (node->type == NODE_FUNC_DECL) {
            const char *fname = arena_strndup(cg->arena,
                node->data.func.name->data.ident.name.data,
                node->data.func.name->data.ident.name.len);
            if (strcmp(fname, "main") == 0) {
                has_main = true;
            }
            if (node->data.func.has_test) {
                test_func_count++;
            }
        }
    }

    /* If @test functions exist but no main(), auto-generate a test dispatcher */
    bool has_test_harness = false;
    if (test_func_count > 0 && !has_main && !cg->has_layout) {
        has_test_harness = true;
        cg_comment(cg, "Auto-generated test dispatcher (no main() found, @test functions present)");
        cg_comment(cg, "Calls all @test functions, returns __test_failures count");

        /* Emit main dispatcher in .text */
        cg_write(cg, "section .text\n\n");

        /* main: call all @test functions */
        cg_write(cg, "main:\n");
        cg_inst1(cg, "push", "rbp");
        cg_inst1(cg, "mov", "rbp, rsp");

        for (int i = 0; i < program->data.list.count; i++) {
            AstNode *node = program->data.list.items[i];
            if (node->type != NODE_FUNC_DECL || !node->data.func.has_test) continue;
            const char *fname = arena_strndup(cg->arena,
                node->data.func.name->data.ident.name.data,
                node->data.func.name->data.ident.name.len);
            cg_write_fmt(cg, "    call %s\n", fname);
        }

        /* Return __test_failures */
        cg_inst(cg, "mov rax, [__test_failures]");
        cg_write(cg, "    leave\n");
        cg_write(cg, "    ret\n\n");
    }

    /* First pass: scan for functions with @entry(addr), @layout, or @kernel_layout attributes */
    cg->entry_addr = 0;
    cg->entry_func = NULL;
    cg->has_layout = false;
    cg->layout_start = 0;
    cg->layout_max = 0;
    cg->layout_bits = 0;
    cg->layout_signature = 0;
    cg->layout_file = NULL;
    for (int i = 0; i < program->data.list.count; i++) {
        AstNode *node = program->data.list.items[i];
        if (node->type == NODE_MODULE_DECL) {
            /* Emit module ABI version as a comment */
            if (node->data.module_decl.module_abi_version >= 0) {
                cg_write_fmt(cg, "; Module ABI version: %d\n", node->data.module_decl.module_abi_version);
            }
        } else if (node->type == NODE_FUNC_DECL) {
            if (node->data.func.entry_addr != -1 && !cg->entry_func) {
                cg->entry_addr = node->data.func.entry_addr;
                cg->entry_func = arena_strndup(cg->arena,
                    node->data.func.name->data.ident.name.data,
                    node->data.func.name->data.ident.name.len);
                /* first entry-point function wins */
            }
            if (node->data.func.has_layout) {
                cg->has_layout = true;
                cg->layout_start = (int64_t)node->data.func.layout_start;
                cg->layout_max = (int64_t)node->data.func.layout_max;
                cg->layout_bits = node->data.func.layout_bits;
                cg->layout_signature = node->data.func.layout_signature;
                if (node->data.func.layout_file.len > 0) {
                    cg->layout_file = arena_strndup(cg->arena,
                        node->data.func.layout_file.data,
                        node->data.func.layout_file.len);
                }
            }
            if (node->data.func.is_kernel_layout) {
                cg_verify_kernel_layout(cg, node);
            }
        }
    }

    /* Target-specific directives */
    bool is_macho = (cg->target == TARGET_MACHO64);
    if (!is_macho && !cg->has_layout) {
        cg_write(cg, "bits 64\n");
    }
    if (!cg->has_layout) {
        if (cg->target != TARGET_BOOT) {
            cg_write(cg, "default rel\n");
        }
        cg_write(cg, "\n");
    }

    /* Emit const declarations as NASM equ directives — only for non-layout targets */
    if (!cg->has_layout) {
        for (int i = 0; i < program->data.list.count; i++) {
            AstNode *node = program->data.list.items[i];
            if (node->type == NODE_CONST_DECL) {
                AstNode *val = node->data.let_decl.value;
                if (val && val->type == NODE_LITERAL_INT) {
                    StringView name = node->data.let_decl.name->data.ident.name;
                    cg_write_fmt(cg, "%.*s equ %llu\n",
                        (int)name.len, name.data,
                        (unsigned long long)val->data.literal.int_val);
                }
            }
        }
        cg_write(cg, "\n");
    }

    /* Emit top-level asm blocks after bits/default/const but before section .text */
    for (int i = 0; i < program->data.list.count; i++) {
        AstNode *node = program->data.list.items[i];
        if (node->type == NODE_ASM_BLOCK) {
            if (node->data.asm_block.text) {
                StringView asm_text = node->data.asm_block.text->data.literal.string_val;
                if (asm_text.len > 0) {
                    cg_write(cg, "; top-level asm block\n");
                    const char *p = asm_text.data;
                    const char *end = p + asm_text.len;
                    while (p < end) {
                        const char *line_start = p;
                        while (p < end && *p != '\n') p++;
                        if (p > line_start) {
                            /* Strip Aether comments (//) from asm block output */
                            const char *s_trim = line_start;
                            while (s_trim < p && (*s_trim == ' ' || *s_trim == '\t')) s_trim++;
                            if (s_trim + 1 < p && s_trim[0] == '/' && s_trim[1] == '/') {
                                /* Skip this line entirely — it's an Aether comment */
                            } else {
                                cg_write_fmt(cg, "%.*s\n", (int)(p - line_start), line_start);
                            }
                        } else {
                            cg_write(cg, "\n");
                        }
                        if (p < end) p++;
                    }
                    cg_write(cg, "; end top-level asm block\n\n");
                }
            }
        }
    }

    /* If @layout is set, emit bits, org, and auto-padding */
    if (cg->has_layout) {
        /* Emit bits directive from @layout(bits=N), default 64 */
        int bits = cg->layout_bits;
        if (bits == 0) bits = 64;
        cg_write_fmt(cg, "bits %d\n", bits);
        /* Emit org from @layout(start=N) */
        if (cg->layout_start > 0) {
            cg_write_fmt(cg, "[org 0x%lx]\n", (unsigned long)cg->layout_start);
        }
        cg_write_fmt(cg, "; Layout: start=0x%lx, max=%ld bytes\n",
            (unsigned long)cg->layout_start, (unsigned long)cg->layout_max);
    } else {
        cg_write(cg, "section .text\n\n");
    }

    /* Entry point — skip for @layout (flat binaries define their own entry) */
    /* Also skip for .aelib libraries and modules (no entry point needed) */
    if (!cg->has_layout && cg->target != TARGET_LIB && cg->target != TARGET_MODULE) {
        if (cg->entry_func) {
            /* @entry(addr) is set — function IS the entry point directly */
            cg_write_fmt(cg, "; Entry point: %s at 0x%lx\n", cg->entry_func, (unsigned long)cg->entry_addr);
            cg_write_fmt(cg, "global %s\n", cg->entry_func);
            /* For host targets, we still need an OS-visible entry wrapper */
            if (is_macho) {
                const char *entry = "_aether_entry";
                cg_write_fmt(cg, "global %s\n", entry);
                cg_write_fmt(cg, "%s:\n", entry);
                cg_inst1(cg, "mov", "rbp, rsp");
                cg_comment(cg, "call entry function");
                cg_write_fmt(cg, "    call %s\n", cg->entry_func);
                cg_comment(cg, "macOS exit(rdi = rax)");
                cg_inst1(cg, "mov", "rdi, rax");
                cg_inst1(cg, "mov", "rax, 0x2000001");
                cg_inst(cg, "syscall");
                cg_inst(cg, "hlt");
                cg_write(cg, "\n");
            } else if (cg->target == TARGET_ELF64_HOST) {
                const char *entry = "_start";
                cg_write_fmt(cg, "global %s\n", entry);
                cg_write_fmt(cg, "%s:\n", entry);
                cg_inst1(cg, "mov", "rbp, rsp");
                cg_comment(cg, "call entry function");
                cg_write_fmt(cg, "    call %s\n", cg->entry_func);
                cg_comment(cg, "Linux exit(rdi = rax)");
                cg_inst1(cg, "mov", "rdi, rax");
                cg_inst1(cg, "mov", "rax, 60");
                cg_inst(cg, "syscall");
                cg_inst(cg, "hlt");
                cg_write(cg, "\n");
            }
            /* For freestanding/kernel/module/binary: linker script handles ENTRY(func_name) — no wrapper needed */
        } else {
            /* Default entry point: wrapper calls main(), then exits */
            const char *entry;
            if (is_macho) {
                entry = "_aether_entry";  /* Mach-O: custom entry, linker -e flag */
            } else if (cg->target == TARGET_UNIVERSAL || cg->target == TARGET_UNIVERSAL_ALL) {
                entry = "_aether_entry";  /* Universal: trampoline defines _start, jumps to _aether_entry */
            } else {
                entry = "_start";          /* ELF: ENTRY(_start) in linker script */
            }
            cg_write_fmt(cg, "global %s\n", entry);
            cg_write_fmt(cg, "%s:\n", entry);
            cg_inst1(cg, "mov", "rbp, rsp");
            cg_comment(cg, "read args from registers (SysV ABI: rdi=argc, rsi=argv)");
            cg_inst(cg, "cmp rdi, 1");         /* argc > 1? */
            cg_inst(cg, "jle .main_no_arg");
            cg_inst(cg, "mov r15, [rsi+8]");   /* r15 = argv[1] (callee-saved) */
            cg_comment(cg, "strlen(argv[1])");
            cg_inst(cg, "xor rcx, rcx");
            cg_write(cg, ".main_strlen:\n");
            cg_inst(cg, "cmp byte [r15+rcx], 0");
            cg_inst(cg, "je .main_strlen_done");
            cg_inst1(cg, "inc", "rcx");
            cg_inst(cg, "jmp .main_strlen");
            cg_write(cg, ".main_strlen_done:\n");
            cg_inst1(cg, "mov", "r14, rcx");   /* r14 = strlen (callee-saved) */
            cg_inst(cg, "jmp .main_call");
            cg_write(cg, ".main_no_arg:\n");
            cg_inst(cg, "xor r15, r15");       /* r15 = 0 */
            cg_inst(cg, "xor r14, r14");       /* r14 = 0 */
            cg_write(cg, ".main_call:\n");
            /* Safe to init segfault handler now */
            if (cg->target == TARGET_MACHO64 || cg->target == TARGET_ELF64_HOST) {
                cg_comment(cg, "init segfault handler");
                if (cg->target == TARGET_MACHO64) {
                    cg_inst(cg, "call _aether_initSegfault");
                } else {
                    cg_inst(cg, "call aether_initSegfault");
                }
            }
            cg_comment(cg, "restore args from callee-saved regs");
            cg_inst1(cg, "mov", "rdi, r15");   /* rdi = argv[1] or 0 */
            cg_inst1(cg, "mov", "rsi, r14");   /* rsi = strlen or 0 */
            cg_inst(cg, "call main");

            if (is_macho) {
                cg_comment(cg, "macOS exit(rdi = rax)");
                cg_inst1(cg, "mov", "rdi, rax");
                cg_inst1(cg, "mov", "rax, 0x2000001");
                cg_inst(cg, "syscall");
            } else if (cg->target == TARGET_ELF64_HOST) {
                cg_comment(cg, "Linux exit(rdi = rax)");
                cg_inst1(cg, "mov", "rdi, rax");
                cg_inst1(cg, "mov", "rax, 60");
                cg_inst(cg, "syscall");
            } else if (cg->target == TARGET_BINARY) {
                cg_comment(cg, "Aether OS binary: ret to shell after main returns");
                cg_inst(cg, "ret");
            } else if (cg->target == TARGET_MODULE) {
                cg_comment(cg, "module: no entry wrapper needed — kernel calls mod_init directly");
            } else {
                cg_comment(cg, "freestanding: just hlt after main returns");
                cg_inst(cg, "hlt");
            }
            cg_inst(cg, "hlt");
            cg_write(cg, "\n");
        }
    }

    /* Emit runtime helpers and data sections — BEFORE user functions */
    if (!cg->has_layout) {
        bool needs_runtime = (cg->target == TARGET_MACHO64 || cg->target == TARGET_ELF64_HOST || cg->target == TARGET_BINARY || cg->target == TARGET_LIB);
        if (needs_runtime) {
            /* Bump allocator state in .bss */
            cg_write(cg, "section .bss\n");
            cg_write(cg, "__aether_heap_start: resq 1\n");
            cg_write(cg, "__aether_heap_cur:   resq 1\n");
            cg_write(cg, "__aether_heap_end:   resq 1\n");
            cg_write(cg, "__aether_region_cur: resq 1\n");
            cg_write(cg, "__aether_region_end: resq 1\n");
            /* Segfault jump buffer — set by try blocks for hardware fault catch */
            cg_write(cg, "__aether_segfault_jmpbuf: resb 200\n");
            if (cg->target == TARGET_BINARY) {
                cg_write(cg, "__aether_heap_buf:  resb 256\n");
            }
            cg_write(cg, "\n");

            cg_write(cg, "section .text\n");
            /* __aether_alloc */
            cg_write(cg, "; __aether_alloc(rdi: size) -> rax: ptr\n");
            cg_write(cg, "; If region is active, bump from region first.\n");
            cg_write(cg, "__aether_alloc:\n");
            cg_inst1(cg, "push", "rbp");
            cg_inst1(cg, "mov", "rbp, rsp");
            cg_inst(cg, "add rdi, 15");
            cg_inst(cg, "and rdi, ~15");
            cg_inst(cg, "mov rax, [rel __aether_region_cur]");
            cg_inst1(cg, "test", "rax, rax");
            cg_inst(cg, "jz LA_heap");
            cg_inst(cg, "lea rcx, [rax + rdi]");
            cg_inst(cg, "cmp rcx, [rel __aether_region_end]");
            cg_inst(cg, "jbe LA_region_ok");
            cg_inst(cg, "jmp LA_heap");
            cg_write(cg, "LA_region_ok:\n");
            cg_inst(cg, "mov [rel __aether_region_cur], rcx");
            cg_inst1(cg, "mov", "rsp, rbp");
            cg_inst1(cg, "pop", "rbp");
            cg_inst(cg, "ret");
            cg_write(cg, "LA_heap:\n");
            cg_inst1(cg, "push", "rdi");
            cg_write(cg, "LA_init:\n");
            if (cg->target == TARGET_BINARY) {
                /* Binary target: use a fixed BSS buffer instead of mmap */
                cg_inst(cg, "mov rax, [rel __aether_heap_start]");
                cg_inst1(cg, "test", "rax, rax");
                cg_inst(cg, "jnz LA_try");
                cg_inst(cg, "lea rax, [rel __aether_heap_buf]");
                cg_inst(cg, "mov [rel __aether_heap_start], rax");
                cg_inst(cg, "lea rcx, [rax + 8]");
                cg_inst(cg, "mov [rel __aether_heap_cur], rcx");
                cg_inst(cg, "lea rcx, [rax + 65536]");
                cg_inst(cg, "mov [rel __aether_heap_end], rcx");
            } else if (cg->target == TARGET_MACHO64) {
                cg_inst1(cg, "mov", "rdi, 0");
                cg_inst1(cg, "mov", "rsi, 65536");
                cg_inst1(cg, "mov", "rdx, 3");
                cg_inst1(cg, "mov", "r10, 0x1002");
                cg_inst1(cg, "mov", "r8, -1");
                cg_inst1(cg, "xor", "r9, r9");
                cg_inst1(cg, "mov", "rax, 0x20000C5");
            } else {
                cg_inst1(cg, "mov", "rdi, 0");
                cg_inst1(cg, "mov", "rsi, 65536");
                cg_inst1(cg, "mov", "rdx, 3");
                cg_inst1(cg, "mov", "r10, 0x22");
                cg_inst1(cg, "mov", "r8, -1");
                cg_inst1(cg, "xor", "r9, r9");
                cg_inst1(cg, "mov", "rax, 9");
            }
            cg_inst(cg, "syscall");
            cg_inst(cg, "mov [rel __aether_heap_start], rax");
            cg_inst(cg, "lea rcx, [rax + 8]");
            cg_inst(cg, "mov [rel __aether_heap_cur], rcx");
            cg_inst(cg, "lea rcx, [rax + 65536]");
            cg_inst(cg, "mov [rel __aether_heap_end], rcx");
            cg_write(cg, "LA_try:\n");
            cg_inst(cg, "mov rax, [rel __aether_heap_cur]");
            cg_inst(cg, "lea rcx, [rax + rdi]");
            cg_inst(cg, "cmp rcx, [rel __aether_heap_end]");
            cg_inst(cg, "jbe LA_ok");
            if (cg->target == TARGET_BINARY) {
                /* Binary target: no more heap space, just halt */
                cg_inst(cg, "cli");
                cg_write(cg, ".oom:\n");
                cg_inst(cg, "hlt");
                cg_inst(cg, "jmp .oom");
            } else if (cg->target == TARGET_MACHO64) {
                cg_inst1(cg, "mov", "rdi, 0");
                cg_inst1(cg, "mov", "rsi, 65536");
                cg_inst1(cg, "mov", "rdx, 3");
                cg_inst1(cg, "mov", "r10, 0x1002");
                cg_inst1(cg, "mov", "r8, -1");
                cg_inst1(cg, "xor", "r9, r9");
                cg_inst1(cg, "mov", "rax, 0x20000C5");
            } else {
                cg_inst1(cg, "mov", "rdi, 0");
                cg_inst1(cg, "mov", "rsi, 65536");
                cg_inst1(cg, "mov", "rdx, 3");
                cg_inst1(cg, "mov", "r10, 0x22");
                cg_inst1(cg, "mov", "r8, -1");
                cg_inst1(cg, "xor", "r9, r9");
                cg_inst1(cg, "mov", "rax, 9");
            }
            cg_inst(cg, "syscall");
            cg_inst(cg, "lea rcx, [rax + 8]");
            cg_inst(cg, "mov [rel __aether_heap_cur], rcx");
            cg_inst(cg, "lea rcx, [rax + 65536]");
            cg_inst(cg, "mov [rel __aether_heap_end], rcx");
            cg_write(cg, "LA_ok:\n");
            cg_inst(cg, "mov rax, [rel __aether_heap_cur]");
            cg_inst(cg, "add [rel __aether_heap_cur], rdi");
            cg_inst1(cg, "mov", "rsp, rbp");
            cg_inst1(cg, "pop", "rbp");
            cg_inst(cg, "ret");
            cg_write(cg, "\n");

            /* __aether_free — no-op bump */
            cg_write(cg, "; __aether_free(rdi: ptr) — no-op (bump allocator)\n");
            cg_write(cg, "__aether_free:\n");
            cg_inst(cg, "ret");
            cg_write(cg, "\n");

            /* __aether_concat(left: ptr, right: ptr) -> rax: ptr */
            cg_write(cg, "; __aether_concat(left: ptr, right: ptr) -> rax: ptr\n");
            cg_write(cg, "; Concatenates two null-terminated strings, returns new string\n");
            cg_write(cg, "__aether_concat:\n");
            cg_inst1(cg, "push", "rbp");
            cg_inst1(cg, "mov", "rbp, rsp");
            cg_inst1(cg, "push", "r12");
            cg_inst1(cg, "push", "r13");
            cg_inst1(cg, "push", "r14");
            cg_inst1(cg, "push", "r15");
            /* Args: call pushed ret_addr, then push rbp; mov rbp,rsp.
               After prologue: [rbp]=old_rbp, [rbp+8]=ret_addr.
               The 4 pushes (r12-r15) after mov rbp,rsp do not move rbp.
               [rbp+16] = right arg (pushed second/last by caller)
               [rbp+24] = left arg (pushed first by caller) */
            cg_inst(cg, "mov r12, [rbp+24]");  /* r12 = left ptr */
            cg_inst(cg, "mov r13, [rbp+16]");  /* r13 = right ptr */
            /* strlen(left) — handle null pointer */
            cg_inst(cg, "test r12, r12");
            cg_inst(cg, "jz LA_concat_left_null");
            cg_inst1(cg, "xor", "rcx, rcx");
            cg_write(cg, "LA_concat_strlen_left:\n");
            cg_inst(cg, "cmp byte [r12+rcx], 0");
            cg_inst(cg, "jz LA_concat_left_strlen_done");
            cg_inst1(cg, "inc", "rcx");
            cg_inst(cg, "jmp LA_concat_strlen_left");
            cg_write(cg, "LA_concat_left_strlen_done:\n");
            cg_inst1(cg, "mov", "r14, rcx");  /* r14 = left_len */
            cg_inst(cg, "jmp LA_concat_right_start");
            cg_write(cg, "LA_concat_left_null:\n");
            cg_inst1(cg, "xor", "r14, r14");  /* r14 = 0 */
            cg_write(cg, "LA_concat_right_start:\n");
            /* strlen(right) — handle null pointer */
            cg_inst(cg, "test r13, r13");
            cg_inst(cg, "jz LA_concat_right_null");
            cg_inst1(cg, "xor", "rcx, rcx");
            cg_write(cg, "LA_concat_strlen_right:\n");
            cg_inst(cg, "cmp byte [r13+rcx], 0");
            cg_inst(cg, "jz LA_concat_right_strlen_done");
            cg_inst1(cg, "inc", "rcx");
            cg_inst(cg, "jmp LA_concat_strlen_right");
            cg_write(cg, "LA_concat_right_strlen_done:\n");
            cg_inst1(cg, "mov", "r15, rcx");  /* r15 = right_len */
            cg_inst(cg, "jmp LA_concat_both_done");
            cg_write(cg, "LA_concat_right_null:\n");
            cg_inst1(cg, "xor", "r15, r15");  /* r15 = 0 */
            cg_write(cg, "LA_concat_both_done:\n");
            /* total = left_len + right_len + 1 */
            cg_inst1(cg, "lea", "rdi, [r14+r15+1]");
            cg_inst(cg, "call __aether_alloc");
            /* rax = allocated buffer, save it */
            cg_inst1(cg, "mov", "r12, rax");  /* r12 = buffer ptr (overwrites left ptr, but we still have it in [rbp+24]) */
            /* Copy left string */
            cg_inst(cg, "mov rsi, [rbp+24]");  /* src = left ptr (re-read from stack args) */
            cg_inst1(cg, "mov", "rdi, r12");  /* dest = buffer */
            cg_inst1(cg, "mov", "rdx, r14");  /* count = left_len */
            cg_inst(cg, "test rdx, rdx");
            cg_inst(cg, "jz LA_concat_skip_left");
            cg_inst(cg, "call LA_concat_memcpy");
            cg_write(cg, "LA_concat_skip_left:\n");
            /* Advance past left */
            cg_inst1(cg, "add", "rdi, r14");
            /* Copy right string */
            cg_inst1(cg, "mov", "rsi, r13");  /* src = right ptr */
            cg_inst1(cg, "mov", "rdx, r15");  /* count = right_len */
            cg_inst(cg, "test rdx, rdx");
            cg_inst(cg, "jz LA_concat_skip_right");
            cg_inst(cg, "call LA_concat_memcpy");
            cg_write(cg, "LA_concat_skip_right:\n");
            /* Null-terminate */
            cg_inst(cg, "mov byte [rdi+r15], 0");
            /* Return buffer ptr in rax */
            cg_inst1(cg, "mov", "rax, r12");
            cg_inst1(cg, "pop", "r15");
            cg_inst1(cg, "pop", "r14");
            cg_inst1(cg, "pop", "r13");
            cg_inst1(cg, "pop", "r12");
            cg_inst1(cg, "mov", "rsp, rbp");
            cg_inst1(cg, "pop", "rbp");
            cg_inst(cg, "ret");
            cg_write(cg, "\n");
            /* memcpy helper: rdi=dest, rsi=src, rdx=count */
            cg_write(cg, "LA_concat_memcpy:\n");
            cg_inst1(cg, "xor", "rcx, rcx");
            cg_write(cg, "LA_concat_memcpy_loop:\n");
            cg_inst(cg, "cmp rcx, rdx");
            cg_inst(cg, "jae LA_concat_memcpy_done");
            cg_inst(cg, "mov al, [rsi+rcx]");
            cg_inst(cg, "mov [rdi+rcx], al");
            cg_inst1(cg, "inc", "rcx");
            cg_inst(cg, "jmp LA_concat_memcpy_loop");
            cg_write(cg, "LA_concat_memcpy_done:\n");
            cg_inst(cg, "ret");
            cg_write(cg, "\n");

            /* __aether_itoa(rdi: u64) -> rax: ptr — converts u64 to decimal string */
            cg_write(cg, "; __aether_itoa(rdi: u64) -> rax: ptr\n");
            cg_write(cg, "; Converts unsigned 64-bit integer to decimal string (allocated)\n");
            cg_write(cg, "__aether_itoa:\n");
            cg_inst1(cg, "push", "rbp");
            cg_inst1(cg, "mov", "rbp, rsp");
            cg_inst1(cg, "push", "r12");
            cg_inst1(cg, "push", "r13");
            cg_inst1(cg, "push", "r14");
            /* rdi = value. Allocate 21 bytes (max 20 digits + null) */
            cg_inst1(cg, "mov", "r12, rdi");   /* r12 = value */
            cg_inst1(cg, "mov", "rdi, 21");
            cg_inst(cg, "call __aether_alloc");
            cg_inst1(cg, "mov", "r13, rax");    /* r13 = buffer */
            /* Handle zero case */
            cg_inst1(cg, "test", "r12, r12");
            cg_inst(cg, "jnz LA_itoa_convert");
            cg_inst(cg, "mov byte [r13], '0'");
            cg_inst(cg, "mov byte [r13+1], 0");
            cg_inst1(cg, "mov", "rax, r13");
            cg_inst1(cg, "pop", "r14");
            cg_inst1(cg, "pop", "r13");
            cg_inst1(cg, "pop", "r12");
            cg_inst1(cg, "mov", "rsp, rbp");
            cg_inst1(cg, "pop", "rbp");
            cg_inst(cg, "ret");
            /* Convert: write digits from end backwards */
            cg_write(cg, "LA_itoa_convert:\n");
            cg_inst1(cg, "lea", "r14, [r13+19]");  /* r14 = end of 20-char buffer */
            cg_inst(cg, "mov byte [r14], 0");        /* null terminator */
            cg_write(cg, "LA_itoa_loop:\n");
            cg_inst1(cg, "mov", "rax, r12");
            cg_inst1(cg, "xor", "rdx, rdx");
            cg_inst1(cg, "mov", "rcx, 10");
            cg_inst1(cg, "div", "rcx");              /* rax = quotient, rdx = remainder */
            cg_inst1(cg, "add", "dl, '0'");          /* convert to ASCII */
            cg_inst(cg, "mov [r14], dl");
            cg_inst1(cg, "dec", "r14");
            cg_inst1(cg, "mov", "r12, rax");
            cg_inst1(cg, "test", "rax, rax");
            cg_inst(cg, "jnz LA_itoa_loop");
            /* r14 points to last char written, advance past it for start */
            cg_inst1(cg, "inc", "r14");
            /* Shift string to start of buffer */
            cg_inst1(cg, "mov", "rdi, r13");         /* dest = buffer start */
            cg_inst1(cg, "mov", "rsi, r14");         /* src = first digit */
            /* Compute length */
            cg_inst1(cg, "lea", "rdx, [r13+20]");
            cg_inst1(cg, "sub", "rdx, r14");         /* rdx = length */
            cg_inst(cg, "call LA_concat_memcpy");
            cg_inst(cg, "mov byte [r13+rdx], 0");    /* null terminate at new position */
            cg_inst1(cg, "mov", "rax, r13");
            cg_inst1(cg, "pop", "r14");
            cg_inst1(cg, "pop", "r13");
            cg_inst1(cg, "pop", "r12");
            cg_inst1(cg, "mov", "rsp, rbp");
            cg_inst1(cg, "pop", "rbp");
            cg_inst(cg, "ret");
            cg_write(cg, "\n");

            /* Default drop stubs for all classes */
            for (StructLayout *sl = struct_layouts; sl; sl = sl->next) {
                if (sl->is_class) {
                    cg_write_fmt(cg, "; default %s_drop stub\n", sl->name);
                    cg_write_fmt(cg, "%s_drop:\n", sl->name);
                    cg_inst(cg, "ret");
                    cg_write(cg, "\n");
                }
            }
        }
    }

    /* Generate each function */
    for (int i = 0; i < program->data.list.count; i++) {
        AstNode *node = program->data.list.items[i];
        if (node->type == NODE_FUNC_DECL && node->data.func.body) {
            cg->current_func = node;
            cg_func(cg, node);
            /* If this function has @layout, emit padding to exactly fill max bytes */
            if (node->data.func.has_layout && cg->layout_max > 0) {
                if (cg->layout_signature != 0) {
                    cg_write_fmt(cg, "; @layout padding to %ld bytes (with signature 0x%x)\n",
                        (unsigned long)cg->layout_max, cg->layout_signature);
                    cg_write_fmt(cg, "times %ld-($-$$) db 0\n",
                        (unsigned long)(cg->layout_max - 2));
                    cg_write_fmt(cg, "dw 0x%x\n", cg->layout_signature);
                } else {
                    cg_write_fmt(cg, "; @layout padding to %ld bytes\n", (unsigned long)cg->layout_max);
                    cg_write_fmt(cg, "times %ld-($-$$) db 0\n", (unsigned long)cg->layout_max);
                }
                cg_write(cg, "\n");
            }
        }
    }

    /* Emit source map table for segfault handler (host targets only) */
    if (!cg->has_layout && cg->src_loc_list) {
        cg_write(cg, "section .rodata align=8\n");
        if (cg->target == TARGET_MACHO64) {
            cg_write(cg, "global _aether_source_map\n");
            cg_write(cg, "_aether_source_map:\n");
        } else {
            cg_write(cg, "global aether_source_map\n");
            cg_write(cg, "aether_source_map:\n");
        }
        int file_id = 0;
        for (SrcLocEntry *e = cg->src_loc_list; e; e = e->next) {
            cg_write_fmt(cg, "  dq _aether_src_%d\n", e->label_num);
            cg_write_fmt(cg, "  dq Lfile_%d\n", file_id);
            cg_write_fmt(cg, "  dd %d, %d\n", e->line, e->col);
            file_id++;
        }
        cg_write(cg, "  dq 0, 0\n");  /* sentinel */
        cg_write(cg, "  dd 0, 0\n");
        cg_write(cg, "\n");
        /* Emit file name strings */
        file_id = 0;
        for (SrcLocEntry *e = cg->src_loc_list; e; e = e->next) {
            cg_write_fmt(cg, "Lfile_%d: db \"%s\", 0\n", file_id, e->file);
            file_id++;
        }
        cg_write(cg, "\n");
    }

    /* Emit string table at the end — all string literals are collected during codegen */
    if (string_entries) {
        cg_write(cg, "section .rodata\n");
        for (StringEntry *e = string_entries; e; e = e->next) {
            cg_write_fmt(cg, "Lstr%d: db ", e->label_num);
            cg_write(cg, "\"");
            for (size_t i = 0; i < e->sv.len; i++) {
                unsigned char c = (unsigned char)e->sv.data[i];
                if (c == '"') cg_write(cg, "\\\"");
                else if (c == '\\') cg_write(cg, "\\\\");
                else if (c >= 32 && c < 127) { char buf[2] = {c, 0}; cg_write(cg, buf); }
                else {
                    cg_write_fmt(cg, "\", %u, \"", c);
                }
            }
            cg_write(cg, "\", 0\n");
        }
    }

    cg->output[cg->output_len] = '\0';
    return cg->output;
}

int codegen_write_asm(Codegen *cg, const char *path) {
    FILE *f = fopen(path, "w");
    if (!f) return -1;
    const char *asm_text = codegen_get_asm(cg);
    if (asm_text) fputs(asm_text, f);
    fclose(f);
    return 0;
}

const char *codegen_get_asm(Codegen *cg) {
    return cg->output;
}